services:
  resonate:
    profiles: ["with-resonate"] # use docker --profile with-resonate compose up
    image: resonatehqio/resonate:latest
    command: ["serve"]
    ports:
      - "8001:8001"
      - "50051:50051"

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=/var/lib/grafana/dashboards/default.json
    volumes:
      - ./config/provisioning:/etc/grafana/provisioning
      - ./config/dashboards:/var/lib/grafana/dashboards
    depends_on:
      - prometheus
      - tempo

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml

  tempo:
    image: grafana/tempo:latest
    command: ["-config.file=/etc/tempo.yml"]
    ports:
      - "4317:4317" # OTLP/gRPC
      - "4318:4318" # OTLP/HTTP
    volumes:
      - ./config/tempo.yml:/etc/tempo.yml
