global:
  scrape_interval: 1s

scrape_configs:
  - job_name: "resonate"
    static_configs:
      - targets:
          - "host.docker.internal:9090"
          - "resonate:9090" # when running with the with-resonate profile
